micronaut:
  application:
    name: countryFunction
datasources:
  default:
    ocid: ocid1.autonomousdatabase.oc1.ap-tokyo-1.anxhiljrssl65iqalxxdbeycxkf4hgewvzttayfdfw67b6puagc5ezwjsruq
    walletPassword: ${countryDS.walletPassword}
    username: ${countryDS.user}
    password: ${countryDS.password}
jpa:
  default:
    entity-scan: com.oracle.jp.fn.country
    properties:
      hibernate:
        hbm2ddl:
          auto: update

oci:
  config:
    resource-principal:
      enabled: true
  vault:
    config:
      enabled: true
    vaults:
      - ocid: ocid1.vault.oc1.ap-tokyo-1.cjqxrot6aahqq.abxhiljr4lp4tzwk2d7urnley6calycu44fvkbtryozqywvto3di6y3anviq
        compartment-ocid: ocid1.compartment.oc1..aaaaaaaanjtbllhqxcg67dq7em3vto2mvsbc6pbgk4pw6cx37afzk3tngmoa