micronaut:
  application:
    name: countryFunction
datasources:
  default:
    driverClassName: oracle.jdbc.OracleDriver
    db-type: oracle
    schema-generate: CREATE_DROP
    dialect: ORACLE
jpa.default.properties.hibernate.hbm2ddl.auto: update
