micronaut:
  application:
    name: countryFunction
datasources:
  default:
    driverClassName: oracle.jdbc.OracleDriver
    db-type: oracle
#    schema-generate: CREATE_DROP
    dialect: ORACLE
    url: jdbc:oracle:thin:@shukawamatp_high?TNS_ADMIN=/home/shukawam/work/wallet/Wallet_shukawamatp
    username: shukawam
    password: jnfRX&Na0001
jpa:
  default:
    entity-scan: com.oracle.jp.fn.country
    properties:
      hibernate:
        hbm2ddl:
          auto: update
