kind: Service
apiVersion: v1
metadata:
  name: country
  labels:
    app: country
spec:
  type: ClusterIP
  selector:
    app: country
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: country
spec:
  replicas: 3
  selector:
    matchLabels:
      app: country
  template:
    metadata:
      labels:
        app: country
        version: v1
    spec:
      containers:
        - name: country
          image: ${DOCKER_SERVER}/${REPOSITORY}/country:${TAG}
          imagePullPolicy: IfNotPresent
          ports:
            - name: api
              containerPort: 8080
          env:
            - name: javax.sql.DataSource.CountryDS.dataSource.url
              valueFrom:
                secretKeyRef:
                  key: url
                  name: atp-secret
            - name: javax.sql.DataSource.CountryDS.dataSource.user
              valueFrom:
                secretKeyRef:
                  key: user
                  name: atp-secret
            - name: javax.sql.DataSource.CountryDS.dataSource.password
              valueFrom:
                secretKeyRef:
                  key: password
                  name: atp-secret
            - name: tracing.data-upload-endpoint
              valueFrom:
                secretKeyRef:
                  key: endpoint
                  name: apm-secret
            - name: tracing.private-data-key
              valueFrom:
                secretKeyRef:
                  key: privateKey
                  name: apm-secret
          readinessProbe:
            httpGet:
              path: /health/ready
              port: api
            initialDelaySeconds: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: api
            initialDelaySeconds: 30
            periodSeconds: 5
          volumeMounts:
            - name: wallet
              mountPath: /tmp/Wallet_shukawamatp
      volumes:
        - name: wallet
          configMap:
            name: wallet
      imagePullSecrets:
        - name: ocir-secret
