kind: Service
apiVersion: v1
metadata:
  name: country
  labels:
    app: country
spec:
  type: NodePort
  selector:
    app: country
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: country
spec:
  replicas: 3
  selector:
    matchLabels:
      app: country
  template:
    metadata:
      labels:
        app: country
        version: v1
    spec:
      containers:
        - name: country
          image: nrt.ocir.io/orasejapan/shukawam/country:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: api
              containerPort: 8080
          env:
            - name: javax.sql.DataSource.CountryDS.dataSource.url
              valueFrom:
                secretKeyRef:
                  key: url
                  name: atp-secret
            - name: javax.sql.DataSource.CountryDS.dataSource.user
              valueFrom:
                secretKeyRef:
                  key: user
                  name: atp-secret
            - name: javax.sql.DataSource.CountryDS.dataSource.password
              valueFrom:
                secretKeyRef:
                  key: password
                  name: atp-secret
          readinessProbe:
            httpGet:
              path: /health/ready
              port: api
            initialDelaySeconds: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: api
            initialDelaySeconds: 30
            periodSeconds: 5
          volumeMounts:
            - name: wallet
              mountPath: /tmp/Wallet_shukawamatp
      volumes:
        - name: wallet
          configMap:
            name: wallet
      imagePullSecrets:
        - name: ocir-secret
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: country
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: code-at-customer.shukawam.com
      http:
        paths:
          - backend:
              service:
                name: country
                port:
                  number: 8080
            path: /
            pathType: Prefix
